//import react router
import { Link } from 'react-router-dom';

//import styles
import './Demo.css'

const Demo = () =>{
    return(
        <div className='Demo'>
            <div className='demo-block' id='demo-block1'>
                <div className='demo-block-content'>
                    <h1>Hohmann Transfer</h1>
                    <p>This is a maneuver to place a geostationary satellite in its corresponding orbit, through a low orbit.</p>
                    <Link to="https://unnamed-mission-visualizer.netlify.app/demo1" target='_blank'><input type="button" value="Play" /></Link>
                </div>
            </div>

            <div className='demo-block' id='demo-block2'>
                <div className='demo-block-content'>
                    <h1>Earth to Mars</h1>
                    <p>It is a simulation of the trajectory of a rocket in the direction of Mars, considering also the orbit of Mars.</p>
                    <Link to="https://unnamed-mission-visualizer.netlify.app/earthtomars" target='_blank'><input type="button" value="Play" /></Link>
                </div>
            </div>

            <div className='demo-block' id='demo-block3'>
                <div className='demo-block-content'>
                    <h1>Trajectory Reader</h1>
                    <p>You can choose a path file generated by GMAT or a similar tool and view it on the web.</p>
                    <Link to="https://unnamed-mission-visualizer.netlify.app/TrajectoryReader.html" target='_blank'><input type="button" value="Play" /></Link>
                </div>
            </div>
        </div>
    );
}

export {Demo}